language: go
go:
  - 1.8.x

# Don't build other branches that are being used for PRs.
# Currently only the master branch is used in this repo.
branches:
  only:
    - master
install:
  - github.com/scmo/foodchain-backend
